### ISSUE TITLE
make fails

### ISSUE THREAD

**Issue by kt97679** [spc476/lua-conmanorg#1]
I'm trying to run make on ubuntu 14.04:
```
$ make
gcc -std=c99 -g -Wall -Wextra -pedantic -fPIC -I/var/tmp/lua/lua-5.3.4/src/ -g -shared -o lib/tcc.so src/tcc.c -ltcc
src/tcc.c: In function ‘tcclua_relocate’:
src/tcc.c:482:3: error: too many arguments to function ‘tcc_relocate’
   size = tcc_relocate(*tcc,NULL);
   ^
In file included from src/tcc.c:49:0:
/usr/include/libtcc.h:96:15: note: declared here
 LIBTCCAPI int tcc_relocate(TCCState *s1);
               ^
src/tcc.c:490:3: error: too many arguments to function ‘tcc_relocate’
   rc = tcc_relocate(*tcc,mem);
   ^
In file included from src/tcc.c:49:0:
/usr/include/libtcc.h:96:15: note: declared here
 LIBTCCAPI int tcc_relocate(TCCState *s1);
               ^
src/tcc.c: In function ‘tcclua_get_symbol’:
src/tcc.c:520:10: warning: ISO C forbids assignment between function pointer and ‘void *’ [-Wpedantic]
     call = tcc_get_symbol(*tcc,luaL_checkstring(L,i));
          ^
make: *** [lib/tcc.so] Error 1
$ 
```
Please advise what I need to do to fix this failure. Thanks!

**Comment by spc476** [comment]
You are using an older version of TCC that isn't supported.  This does work with TCC 0.9.25 and it *should* (maybe) run with a higher version, but it's not tested.  The latest version is available at http://repo.or.cz/tinycc.git.

**Comment by kt97679** [comment]
Thanks for the quick response @spc476 ! How do you suggest to fix this in my case?

**Comment by spc476** [comment]
Um ... download the latest version of TCC that I linked to and use that?  Fix the Lua module to remove the extra parameter? (although I don't know if that will work, and I don't accept a patch for it since there's no way to check for that when compiling)  Skip compiling TCC entirely by removing it from the Makefile? (unless you need to use the module for some reason).  I don't know exactly what you want here ...

**Comment by kt97679** [comment]
Ok, thanks @spc476 . One more question. I've compiled lua from sources and don't want to install it into the system. How I can add your modules to my compiled binary?

**Comment by spc476** [comment]
I write two articles about embedding modules in a Lua executable ([Preloading Lua modules](http://boston.conman.org/2013/03/22.1) and [Preloading Lua modules, part II](http://boston.conman.org/2013/03/23.1)) but that was several years ago---I changed it slightly since then to load the C based modules into packages.preload[].  This does require changes to the main Lua executable (lua.c in the Lua source code) and the Makefile to implement.

You'll also find code to convert arbitrary data (like Lua scripts) info a format that can be compiled by a C compiler (build/bin2c.c in this repo) which can be helpful for this endeavor.

**Comment by spc476** [comment]
I write two articles about embedding modules in a Lua executable ([Preloading Lua modules](http://boston.conman.org/2013/03/22.1) and [Preloading Lua modules, part II](http://boston.conman.org/2013/03/23.1)) but that was several years ago---I changed it slightly since then to load the C based modules into packages.preload[].  This does require changes to the main Lua executable (lua.c in the Lua source code) and the Makefile to implement.

You'll also find code to convert arbitrary data (like Lua scripts) info a format that can be compiled by a C compiler (build/bin2c.c in this repo) which can be helpful for this endeavor.
